export default {
	PATH_CONFIG: false,
	PATH_INFO: false,

	ReadFile: false,
	GetFootage: false,
	Each: false,
	EnsureDir: false,
	EnsureComp: false,
	RGB: false,
	RGBH: false,
	EnumLine: false,
	GetBoxSize: false,
	GetBoxSizeMark: false,
	SetText: false,
	SetAttr: false,

	I: false,
	D: false,
	L: false,
	LinesInfoExtra: false,

	DirLine: false,
	DirVoice: false,
	DirFootage: false,
	DirComp: false,
	CompMain: false,
	CompTest: false,
	CompBack: false,

	AddGlobal: false,
	AddOpener: false,
	AddTitle: false,
	CalcDuration: false,
	AddLine: false,
	AddLineScroll: false,
	AddBGM: false,
	AddEnding: false,
	AddBackGround: false,
	AddLineBackGround: false,
	AddCounter: false,
	AddGlobalMark: false,

	OffsetSplashBackground: false,

	AddProperty: false,
	AddShape: false,
	AddText: false,
	Ease1: false,
	Ease2: false,
	SetEase: false,
};
